#add activeCampaignTrigger.json
[
    # Node-level (n8n node definition)
    "node_name",
    "node_display_name",
    "node_description",
    "node_properties",

    # NEW (to preserve HTML/markup in descriptions like the <a href=...> in this node) :contentReference[oaicite:0]{index=0}
    "node_description_format",          # e.g., "plain" | "html" | "markdown"

    # Parameter-level (shared schema for each property/parameter)
    "param_display_name",
    "param_name",
    "param_type",
    "param_default",
    "param_required",
    "param_description",
    "param_placeholder",
    "param_no_data_expression",
    "param_display_options",
    "param_type_options",

    # NEW (forward-compatible raw containers; typeOptions / options often evolve across nodes) :contentReference[oaicite:1]{index=1}
    "param_description_format",         # e.g., "plain" | "html" | "markdown"
    "param_type_options_raw",           # full dict snapshot of typeOptions (lossless)
    "param_options_raw",                # full list snapshot of options (lossless)

    # Expanded from activeCampaignTool.json: typeOptions frequently carries structured constraints/behaviors
    "param_type_options_load_options_method",
    "param_type_options_multiple_values",
    "param_type_options_min_value",
    "param_type_options_max_value",
    "param_type_options_rows",

    "param_options",
    "param_values",

    "param_parent_name",
    "param_path",
    "param_level",

    "param_group_display_name",
    "param_group_name",

    "option_name",
    "option_value",
    "option_action",
    "option_description",

    # Domain-normalized argument names observed in this node's schema (reusable across nodes)
    "an_additionalFields",
    "an_address",
    "an_address_lines",
    "an_attendanceId",
    "an_browser_url",
    "an_comments",
    "an_country",
    "an_description",
    "an_email_addresses",
    "an_end_date",
    "an_eventId",
    "an_family_name",
    "an_featured_image_url",
    "an_given_name",
    "an_instructions",
    "an_language",
    "an_languages_spoken",
    "an_latitude",
    "an_limit",
    "an_locality",
    "an_location",
    "an_location_fields",
    "an_name",
    "an_number",
    "an_operation",
    "an_originSystem",
    "an_personId",
    "an_petitionId",
    "an_petition_text",
    "an_phone_numbers",
    "an_postal_addresses",
    "an_postal_addresses_fields",
    "an_postal_code",
    "an_primary",
    "an_region",
    "an_resource",
    "an_returnAll",
    "an_signatureId",
    "an_simple",
    "an_start_date",
    "an_status",
    "an_tagId",
    "an_taggingId",
    "an_target",
    "an_title",
    "an_updateFields",

    # Added from activeCampaignTool.json (IDs, CRM/contact fields, filters, ordering, and deal-specific fields)
    "an_accountId",
    "an_accountContactId",
    "an_accountUrl",
    "an_contactId",
    "an_contactTagId",
    "an_customFieldId",
    "an_field",
    "an_fields",
    "an_fieldValue",
    "an_fieldValues",
    "an_firstName",
    "an_lastName",
    "an_phone",
    "an_updateIfExists",

    "an_datetime",
    "an_email_like",
    "an_exclude",
    "an_formid",
    "an_listid",
    "an_search",
    "an_segmentid",
    "an_seriesid",
    "an_tagid",
    "an_waitid",

    "an_filters_created_before",
    "an_filters_created_after",
    "an_filters_updated_before",
    "an_filters_updated_after",

    "an_orderBy",
    "an_orders_cdate",
    "an_orders_email",
    "an_orders_first_name",
    "an_orders_last_name",
    "an_orders_name",
    "an_orders_score",

    "an_currency",
    "an_value",
    "an_group",
    "an_stage",
    "an_owner",
    "an_percent",
    "an_dealId",
]
