#add actionNetwork.json
[
    # Node-level (n8n node definition)
    "node_name",
    "node_display_name",
    "node_description",
    "node_properties",

    # Parameter-level (shared schema for each property/parameter)
    "param_display_name",
    "param_name",
    "param_type",
    "param_default",
    "param_required",
    "param_description",
    "param_placeholder",
    "param_no_data_expression",
    "param_display_options",
    "param_type_options",
    "param_options",
    "param_values",

    # Option-level (shared schema for each options item)
    "option_name",
    "option_value",
    "option_action",

    # Action Network node-specific parameter names (namespaced to avoid ambiguity)
    "an_additionalFields",
    "an_address",
    "an_address_lines",
    "an_attendanceId",
    "an_browser_url",
    "an_comments",
    "an_country",
    "an_description",
    "an_email_addresses",
    "an_end_date",
    "an_eventId",
    "an_family_name",
    "an_featured_image_url",
    "an_given_name",
    "an_instructions",
    "an_language",
    "an_languages_spoken",
    "an_latitude",
    "an_limit",
    "an_locality",
    "an_location",
    "an_location_fields",
    "an_name",
    "an_number",
    "an_operation",
    "an_originSystem",
    "an_personId",
    "an_petitionId",
    "an_petition_text",
    "an_phone_numbers",
    "an_postal_addresses",
    "an_postal_addresses_fields",
    "an_postal_code",
    "an_primary",
    "an_region",
    "an_resource",
    "an_returnAll",
    "an_signatureId",
    "an_simple",
    "an_start_date",
    "an_status",
    "an_tagId",
    "an_taggingId",
    "an_target",
    "an_title",
    "an_updateFields",
]
